# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pageextensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageextension',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
