# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 19:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageextensions', '0003_auto_20200813_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageextension',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
